### ISSUE TITLE
"close lecture" is not working

### ISSUE THREAD

**Issue by DavidBadura** [tolry/talkly#106]
```
(index):47045 Uncaught (in promise) TypeError: Cannot set property 'value' of undefined
  at Object.i.setTime (https://talkly.de/build/app.js:39:22375)
  at t.value (https://talkly.de/build/app.js:26:12344)
  at t.value (https://talkly.de/build/app.js:35:10039)
  at r (https://talkly.de/build/app.js:68:30478)
  at Object.i.attachRefs (https://talkly.de/build/app.js:68:30700)
  at r (https://talkly.de/build/app.js:10:19825)
  at r.notifyAll (https://talkly.de/build/app.js:32:10616)
  at r.close (https://talkly.de/build/app.js:68:29987)
  at r.closeAll (https://talkly.de/build/app.js:10:26882)
  at r.perform (https://talkly.de/build/app.js:10:26326)
```

**Comment by tolry** [comment]
@DavidBadura just used this feature succesfully in a master-checkout today (but did not set a lecture time) - I will try to reproduce this

**Comment by tolry** [comment]
@DavidBadura seems only to happen, if there is already a lecture date set (including a time). If there is not lecture date set, it will work, regardless if the user sets the date (no time possible here) or leave the field empty.
